// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NGameMessage.proto

package cn.jisol.ngame.proto.message;

public final class NGameMessageOuterClass {
  private NGameMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NGameMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NGameMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string action = 1;</code>
     * @return The action.
     */
    java.lang.String getAction();
    /**
     * <code>string action = 1;</code>
     * @return The bytes for action.
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <code>string event = 2;</code>
     * @return The event.
     */
    java.lang.String getEvent();
    /**
     * <code>string event = 2;</code>
     * @return The bytes for event.
     */
    com.google.protobuf.ByteString
        getEventBytes();

    /**
     * <code>int32 uid = 3;</code>
     * @return The uid.
     */
    int getUid();

    /**
     * <code>.google.protobuf.Any message = 4;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>.google.protobuf.Any message = 4;</code>
     * @return The message.
     */
    com.google.protobuf.Any getMessage();
    /**
     * <code>.google.protobuf.Any message = 4;</code>
     */
    com.google.protobuf.AnyOrBuilder getMessageOrBuilder();
  }
  /**
   * Protobuf type {@code NGameMessage}
   */
  public static final class NGameMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NGameMessage)
      NGameMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NGameMessage.newBuilder() to construct.
    private NGameMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NGameMessage() {
      action_ = "";
      event_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NGameMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NGameMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              action_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              event_ = s;
              break;
            }
            case 24: {

              uid_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (message_ != null) {
                subBuilder = message_.toBuilder();
              }
              message_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(message_);
                message_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.jisol.ngame.proto.message.NGameMessageOuterClass.internal_static_NGameMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.jisol.ngame.proto.message.NGameMessageOuterClass.internal_static_NGameMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage.class, cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage.Builder.class);
    }

    public static final int ACTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object action_;
    /**
     * <code>string action = 1;</code>
     * @return The action.
     */
    @java.lang.Override
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <code>string action = 1;</code>
     * @return The bytes for action.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object event_;
    /**
     * <code>string event = 2;</code>
     * @return The event.
     */
    @java.lang.Override
    public java.lang.String getEvent() {
      java.lang.Object ref = event_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        event_ = s;
        return s;
      }
    }
    /**
     * <code>string event = 2;</code>
     * @return The bytes for event.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventBytes() {
      java.lang.Object ref = event_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        event_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UID_FIELD_NUMBER = 3;
    private int uid_;
    /**
     * <code>int32 uid = 3;</code>
     * @return The uid.
     */
    @java.lang.Override
    public int getUid() {
      return uid_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
    private com.google.protobuf.Any message_;
    /**
     * <code>.google.protobuf.Any message = 4;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return message_ != null;
    }
    /**
     * <code>.google.protobuf.Any message = 4;</code>
     * @return The message.
     */
    @java.lang.Override
    public com.google.protobuf.Any getMessage() {
      return message_ == null ? com.google.protobuf.Any.getDefaultInstance() : message_;
    }
    /**
     * <code>.google.protobuf.Any message = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getMessageOrBuilder() {
      return getMessage();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getActionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, action_);
      }
      if (!getEventBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, event_);
      }
      if (uid_ != 0) {
        output.writeInt32(3, uid_);
      }
      if (message_ != null) {
        output.writeMessage(4, getMessage());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getActionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, action_);
      }
      if (!getEventBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, event_);
      }
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, uid_);
      }
      if (message_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getMessage());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage)) {
        return super.equals(obj);
      }
      cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage other = (cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage) obj;

      if (!getAction()
          .equals(other.getAction())) return false;
      if (!getEvent()
          .equals(other.getEvent())) return false;
      if (getUid()
          != other.getUid()) return false;
      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage()
            .equals(other.getMessage())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + EVENT_FIELD_NUMBER;
      hash = (53 * hash) + getEvent().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NGameMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NGameMessage)
        cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.jisol.ngame.proto.message.NGameMessageOuterClass.internal_static_NGameMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.jisol.ngame.proto.message.NGameMessageOuterClass.internal_static_NGameMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage.class, cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage.Builder.class);
      }

      // Construct using cn.jisol.ngame.demo.proto.message.NGameMessageOuterClass.NGameMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        action_ = "";

        event_ = "";

        uid_ = 0;

        if (messageBuilder_ == null) {
          message_ = null;
        } else {
          message_ = null;
          messageBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.jisol.ngame.proto.message.NGameMessageOuterClass.internal_static_NGameMessage_descriptor;
      }

      @java.lang.Override
      public cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage getDefaultInstanceForType() {
        return cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage.getDefaultInstance();
      }

      @java.lang.Override
      public cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage build() {
        cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage buildPartial() {
        cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage result = new cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage(this);
        result.action_ = action_;
        result.event_ = event_;
        result.uid_ = uid_;
        if (messageBuilder_ == null) {
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage) {
          return mergeFrom((cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage other) {
        if (other == cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage.getDefaultInstance()) return this;
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          onChanged();
        }
        if (!other.getEvent().isEmpty()) {
          event_ = other.event_;
          onChanged();
        }
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (other.hasMessage()) {
          mergeMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object action_ = "";
      /**
       * <code>string action = 1;</code>
       * @return The action.
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string action = 1;</code>
       * @return The bytes for action.
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string action = 1;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string action = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {

        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <code>string action = 1;</code>
       * @param value The bytes for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        action_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object event_ = "";
      /**
       * <code>string event = 2;</code>
       * @return The event.
       */
      public java.lang.String getEvent() {
        java.lang.Object ref = event_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          event_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string event = 2;</code>
       * @return The bytes for event.
       */
      public com.google.protobuf.ByteString
          getEventBytes() {
        java.lang.Object ref = event_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          event_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string event = 2;</code>
       * @param value The event to set.
       * @return This builder for chaining.
       */
      public Builder setEvent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        event_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string event = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEvent() {

        event_ = getDefaultInstance().getEvent();
        onChanged();
        return this;
      }
      /**
       * <code>string event = 2;</code>
       * @param value The bytes for event to set.
       * @return This builder for chaining.
       */
      public Builder setEventBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        event_ = value;
        onChanged();
        return this;
      }

      private int uid_ ;
      /**
       * <code>int32 uid = 3;</code>
       * @return The uid.
       */
      @java.lang.Override
      public int getUid() {
        return uid_;
      }
      /**
       * <code>int32 uid = 3;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(int value) {

        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {

        uid_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any message_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> messageBuilder_;
      /**
       * <code>.google.protobuf.Any message = 4;</code>
       * @return Whether the message field is set.
       */
      public boolean hasMessage() {
        return messageBuilder_ != null || message_ != null;
      }
      /**
       * <code>.google.protobuf.Any message = 4;</code>
       * @return The message.
       */
      public com.google.protobuf.Any getMessage() {
        if (messageBuilder_ == null) {
          return message_ == null ? com.google.protobuf.Any.getDefaultInstance() : message_;
        } else {
          return messageBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any message = 4;</code>
       */
      public Builder setMessage(com.google.protobuf.Any value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          messageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any message = 4;</code>
       */
      public Builder setMessage(
          com.google.protobuf.Any.Builder builderForValue) {
        if (messageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any message = 4;</code>
       */
      public Builder mergeMessage(com.google.protobuf.Any value) {
        if (messageBuilder_ == null) {
          if (message_ != null) {
            message_ =
              com.google.protobuf.Any.newBuilder(message_).mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          messageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any message = 4;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = null;
          onChanged();
        } else {
          message_ = null;
          messageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any message = 4;</code>
       */
      public com.google.protobuf.Any.Builder getMessageBuilder() {

        onChanged();
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any message = 4;</code>
       */
      public com.google.protobuf.AnyOrBuilder getMessageOrBuilder() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          return message_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : message_;
        }
      }
      /**
       * <code>.google.protobuf.Any message = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getMessage(),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NGameMessage)
    }

    // @@protoc_insertion_point(class_scope:NGameMessage)
    private static final cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage();
    }

    public static cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NGameMessage>
        PARSER = new com.google.protobuf.AbstractParser<NGameMessage>() {
      @java.lang.Override
      public NGameMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NGameMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NGameMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NGameMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.jisol.ngame.proto.message.NGameMessageOuterClass.NGameMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NGameMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NGameMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022NGameMessage.proto\032\031google/protobuf/an" +
      "y.proto\"a\n\014NGameMessage\022\016\n\006action\030\001 \001(\t\022" +
      "\r\n\005event\030\002 \001(\t\022\013\n\003uid\030\003 \001(\005\022%\n\007message\030\004" +
      " \001(\0132\024.google.protobuf.AnyB\036\n\034cn.jisol.n" +
      "game.proto.messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_NGameMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NGameMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NGameMessage_descriptor,
        new java.lang.String[] { "Action", "Event", "Uid", "Message", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
