// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FStateMessage.proto

package cn.jisol.ngame.demo.proto.cocos;

public final class FStateMessage {
  private FStateMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NStateVec3OrBuilder extends
      // @@protoc_insertion_point(interface_extends:NStateVec3)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double x = 1;</code>
     * @return The x.
     */
    double getX();

    /**
     * <code>double y = 2;</code>
     * @return The y.
     */
    double getY();

    /**
     * <code>double z = 3;</code>
     * @return The z.
     */
    double getZ();
  }
  /**
   * Protobuf type {@code NStateVec3}
   */
  public static final class NStateVec3 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NStateVec3)
      NStateVec3OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NStateVec3.newBuilder() to construct.
    private NStateVec3(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NStateVec3() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NStateVec3();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NStateVec3(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              x_ = input.readDouble();
              break;
            }
            case 17: {

              y_ = input.readDouble();
              break;
            }
            case 25: {

              z_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateVec3_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateVec3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3.class, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private double x_;
    /**
     * <code>double x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private double y_;
    /**
     * <code>double y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public double getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private double z_;
    /**
     * <code>double z = 3;</code>
     * @return The z.
     */
    @java.lang.Override
    public double getZ() {
      return z_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        output.writeDouble(1, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        output.writeDouble(2, y_);
      }
      if (java.lang.Double.doubleToRawLongBits(z_) != 0) {
        output.writeDouble(3, z_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      if (java.lang.Double.doubleToRawLongBits(z_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, z_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3)) {
        return super.equals(obj);
      }
      cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 other = (cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3) obj;

      if (java.lang.Double.doubleToLongBits(getX())
          != java.lang.Double.doubleToLongBits(
              other.getX())) return false;
      if (java.lang.Double.doubleToLongBits(getY())
          != java.lang.Double.doubleToLongBits(
              other.getY())) return false;
      if (java.lang.Double.doubleToLongBits(getZ())
          != java.lang.Double.doubleToLongBits(
              other.getZ())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getX()));
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getY()));
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getZ()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NStateVec3}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NStateVec3)
        cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateVec3_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateVec3_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3.class, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3.Builder.class);
      }

      // Construct using cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = 0D;

        y_ = 0D;

        z_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateVec3_descriptor;
      }

      @java.lang.Override
      public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 getDefaultInstanceForType() {
        return cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3.getDefaultInstance();
      }

      @java.lang.Override
      public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 build() {
        cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 buildPartial() {
        cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 result = new cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3(this);
        result.x_ = x_;
        result.y_ = y_;
        result.z_ = z_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3) {
          return mergeFrom((cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 other) {
        if (other == cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3.getDefaultInstance()) return this;
        if (other.getX() != 0D) {
          setX(other.getX());
        }
        if (other.getY() != 0D) {
          setY(other.getY());
        }
        if (other.getZ() != 0D) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double x_ ;
      /**
       * <code>double x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public double getX() {
        return x_;
      }
      /**
       * <code>double x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(double value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>double y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public double getY() {
        return y_;
      }
      /**
       * <code>double y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(double value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        
        y_ = 0D;
        onChanged();
        return this;
      }

      private double z_ ;
      /**
       * <code>double z = 3;</code>
       * @return The z.
       */
      @java.lang.Override
      public double getZ() {
        return z_;
      }
      /**
       * <code>double z = 3;</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(double value) {
        
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double z = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        
        z_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NStateVec3)
    }

    // @@protoc_insertion_point(class_scope:NStateVec3)
    private static final cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3();
    }

    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NStateVec3>
        PARSER = new com.google.protobuf.AbstractParser<NStateVec3>() {
      @java.lang.Override
      public NStateVec3 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NStateVec3(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NStateVec3> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NStateVec3> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateVec3 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NStateMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NStateMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 nId = 1;</code>
     * @return The nId.
     */
    long getNId();

    /**
     * <code>int64 prefab = 2;</code>
     * @return The prefab.
     */
    long getPrefab();

    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
     */
    int getStatesCount();
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
     */
    boolean containsStates(
        java.lang.String key);
    /**
     * Use {@link #getStatesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.Any>
    getStates();
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.Any>
    getStatesMap();
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
     */

    /* nullable */
com.google.protobuf.Any getStatesOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.Any defaultValue);
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
     */

    com.google.protobuf.Any getStatesOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code NStateMessage}
   */
  public static final class NStateMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NStateMessage)
      NStateMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NStateMessage.newBuilder() to construct.
    private NStateMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NStateMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NStateMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NStateMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              nId_ = input.readInt64();
              break;
            }
            case 16: {

              prefab_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                states_ = com.google.protobuf.MapField.newMapField(
                    StatesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Any>
              states__ = input.readMessage(
                  StatesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              states_.getMutableMap().put(
                  states__.getKey(), states__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetStates();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.class, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.Builder.class);
    }

    public static final int NID_FIELD_NUMBER = 1;
    private long nId_;
    /**
     * <code>int64 nId = 1;</code>
     * @return The nId.
     */
    @java.lang.Override
    public long getNId() {
      return nId_;
    }

    public static final int PREFAB_FIELD_NUMBER = 2;
    private long prefab_;
    /**
     * <code>int64 prefab = 2;</code>
     * @return The prefab.
     */
    @java.lang.Override
    public long getPrefab() {
      return prefab_;
    }

    public static final int STATES_FIELD_NUMBER = 3;
    private static final class StatesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.Any> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.Any>newDefaultInstance(
                  cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateMessage_StatesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Any.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.Any> states_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
    internalGetStates() {
      if (states_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StatesDefaultEntryHolder.defaultEntry);
      }
      return states_;
    }

    public int getStatesCount() {
      return internalGetStates().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
     */

    @java.lang.Override
    public boolean containsStates(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetStates().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStatesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Any> getStates() {
      return getStatesMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.google.protobuf.Any> getStatesMap() {
      return internalGetStates().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
     */
    @java.lang.Override

    public com.google.protobuf.Any getStatesOrDefault(
        java.lang.String key,
        com.google.protobuf.Any defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.Any> map =
          internalGetStates().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
     */
    @java.lang.Override

    public com.google.protobuf.Any getStatesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.Any> map =
          internalGetStates().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nId_ != 0L) {
        output.writeInt64(1, nId_);
      }
      if (prefab_ != 0L) {
        output.writeInt64(2, prefab_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetStates(),
          StatesDefaultEntryHolder.defaultEntry,
          3);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, nId_);
      }
      if (prefab_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, prefab_);
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Any> entry
           : internalGetStates().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Any>
        states__ = StatesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, states__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage)) {
        return super.equals(obj);
      }
      cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage other = (cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage) obj;

      if (getNId()
          != other.getNId()) return false;
      if (getPrefab()
          != other.getPrefab()) return false;
      if (!internalGetStates().equals(
          other.internalGetStates())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNId());
      hash = (37 * hash) + PREFAB_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPrefab());
      if (!internalGetStates().getMap().isEmpty()) {
        hash = (37 * hash) + STATES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetStates().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NStateMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NStateMessage)
        cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateMessage_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetStates();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableStates();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.class, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.Builder.class);
      }

      // Construct using cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nId_ = 0L;

        prefab_ = 0L;

        internalGetMutableStates().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateMessage_descriptor;
      }

      @java.lang.Override
      public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage getDefaultInstanceForType() {
        return cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.getDefaultInstance();
      }

      @java.lang.Override
      public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage build() {
        cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage buildPartial() {
        cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage result = new cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage(this);
        int from_bitField0_ = bitField0_;
        result.nId_ = nId_;
        result.prefab_ = prefab_;
        result.states_ = internalGetStates();
        result.states_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage) {
          return mergeFrom((cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage other) {
        if (other == cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.getDefaultInstance()) return this;
        if (other.getNId() != 0L) {
          setNId(other.getNId());
        }
        if (other.getPrefab() != 0L) {
          setPrefab(other.getPrefab());
        }
        internalGetMutableStates().mergeFrom(
            other.internalGetStates());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long nId_ ;
      /**
       * <code>int64 nId = 1;</code>
       * @return The nId.
       */
      @java.lang.Override
      public long getNId() {
        return nId_;
      }
      /**
       * <code>int64 nId = 1;</code>
       * @param value The nId to set.
       * @return This builder for chaining.
       */
      public Builder setNId(long value) {
        
        nId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 nId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNId() {
        
        nId_ = 0L;
        onChanged();
        return this;
      }

      private long prefab_ ;
      /**
       * <code>int64 prefab = 2;</code>
       * @return The prefab.
       */
      @java.lang.Override
      public long getPrefab() {
        return prefab_;
      }
      /**
       * <code>int64 prefab = 2;</code>
       * @param value The prefab to set.
       * @return This builder for chaining.
       */
      public Builder setPrefab(long value) {
        
        prefab_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 prefab = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrefab() {
        
        prefab_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.Any> states_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
      internalGetStates() {
        if (states_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              StatesDefaultEntryHolder.defaultEntry);
        }
        return states_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
      internalGetMutableStates() {
        onChanged();;
        if (states_ == null) {
          states_ = com.google.protobuf.MapField.newMapField(
              StatesDefaultEntryHolder.defaultEntry);
        }
        if (!states_.isMutable()) {
          states_ = states_.copy();
        }
        return states_;
      }

      public int getStatesCount() {
        return internalGetStates().getMap().size();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
       */

      @java.lang.Override
      public boolean containsStates(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetStates().getMap().containsKey(key);
      }
      /**
       * Use {@link #getStatesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Any> getStates() {
        return getStatesMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, com.google.protobuf.Any> getStatesMap() {
        return internalGetStates().getMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
       */
      @java.lang.Override

      public com.google.protobuf.Any getStatesOrDefault(
          java.lang.String key,
          com.google.protobuf.Any defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.google.protobuf.Any> map =
            internalGetStates().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
       */
      @java.lang.Override

      public com.google.protobuf.Any getStatesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.google.protobuf.Any> map =
            internalGetStates().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearStates() {
        internalGetMutableStates().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
       */

      public Builder removeStates(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableStates().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Any>
      getMutableStates() {
        return internalGetMutableStates().getMutableMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
       */
      public Builder putStates(
          java.lang.String key,
          com.google.protobuf.Any value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutableStates().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; states = 3;</code>
       */

      public Builder putAllStates(
          java.util.Map<java.lang.String, com.google.protobuf.Any> values) {
        internalGetMutableStates().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NStateMessage)
    }

    // @@protoc_insertion_point(class_scope:NStateMessage)
    private static final cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage();
    }

    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NStateMessage>
        PARSER = new com.google.protobuf.AbstractParser<NStateMessage>() {
      @java.lang.Override
      public NStateMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NStateMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NStateMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NStateMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NStateMessagesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NStateMessages)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .NStateMessage messages = 1;</code>
     */
    java.util.List<cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage> 
        getMessagesList();
    /**
     * <code>repeated .NStateMessage messages = 1;</code>
     */
    cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage getMessages(int index);
    /**
     * <code>repeated .NStateMessage messages = 1;</code>
     */
    int getMessagesCount();
    /**
     * <code>repeated .NStateMessage messages = 1;</code>
     */
    java.util.List<? extends cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessageOrBuilder> 
        getMessagesOrBuilderList();
    /**
     * <code>repeated .NStateMessage messages = 1;</code>
     */
    cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessageOrBuilder getMessagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code NStateMessages}
   */
  public static final class NStateMessages extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NStateMessages)
      NStateMessagesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NStateMessages.newBuilder() to construct.
    private NStateMessages(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NStateMessages() {
      messages_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NStateMessages();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NStateMessages(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                messages_ = new java.util.ArrayList<cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              messages_.add(
                  input.readMessage(cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateMessages_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateMessages_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages.class, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages.Builder.class);
    }

    public static final int MESSAGES_FIELD_NUMBER = 1;
    private java.util.List<cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage> messages_;
    /**
     * <code>repeated .NStateMessage messages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage> getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated .NStateMessage messages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessageOrBuilder> 
        getMessagesOrBuilderList() {
      return messages_;
    }
    /**
     * <code>repeated .NStateMessage messages = 1;</code>
     */
    @java.lang.Override
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated .NStateMessage messages = 1;</code>
     */
    @java.lang.Override
    public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <code>repeated .NStateMessage messages = 1;</code>
     */
    @java.lang.Override
    public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessageOrBuilder getMessagesOrBuilder(
        int index) {
      return messages_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < messages_.size(); i++) {
        output.writeMessage(1, messages_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < messages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, messages_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages)) {
        return super.equals(obj);
      }
      cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages other = (cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages) obj;

      if (!getMessagesList()
          .equals(other.getMessagesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMessagesCount() > 0) {
        hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + getMessagesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NStateMessages}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NStateMessages)
        cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessagesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateMessages_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateMessages_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages.class, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages.Builder.class);
      }

      // Construct using cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMessagesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.jisol.ngame.demo.proto.cocos.FStateMessage.internal_static_NStateMessages_descriptor;
      }

      @java.lang.Override
      public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages getDefaultInstanceForType() {
        return cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages.getDefaultInstance();
      }

      @java.lang.Override
      public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages build() {
        cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages buildPartial() {
        cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages result = new cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages(this);
        int from_bitField0_ = bitField0_;
        if (messagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            messages_ = java.util.Collections.unmodifiableList(messages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.messages_ = messages_;
        } else {
          result.messages_ = messagesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages) {
          return mergeFrom((cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages other) {
        if (other == cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages.getDefaultInstance()) return this;
        if (messagesBuilder_ == null) {
          if (!other.messages_.isEmpty()) {
            if (messages_.isEmpty()) {
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessagesIsMutable();
              messages_.addAll(other.messages_);
            }
            onChanged();
          }
        } else {
          if (!other.messages_.isEmpty()) {
            if (messagesBuilder_.isEmpty()) {
              messagesBuilder_.dispose();
              messagesBuilder_ = null;
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMessagesFieldBuilder() : null;
            } else {
              messagesBuilder_.addAllMessages(other.messages_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage> messages_ =
        java.util.Collections.emptyList();
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          messages_ = new java.util.ArrayList<cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage>(messages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.Builder, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessageOrBuilder> messagesBuilder_;

      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public java.util.List<cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage> getMessagesList() {
        if (messagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messages_);
        } else {
          return messagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public int getMessagesCount() {
        if (messagesBuilder_ == null) {
          return messages_.size();
        } else {
          return messagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage getMessages(int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);
        } else {
          return messagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public Builder setMessages(
          int index, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.set(index, value);
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public Builder setMessages(
          int index, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.set(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public Builder addMessages(cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public Builder addMessages(
          int index, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(index, value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public Builder addMessages(
          cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public Builder addMessages(
          int index, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public Builder addAllMessages(
          java.lang.Iterable<? extends cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage> values) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messages_);
          onChanged();
        } else {
          messagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public Builder clearMessages() {
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public Builder removeMessages(int index) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.remove(index);
          onChanged();
        } else {
          messagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.Builder getMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessageOrBuilder getMessagesOrBuilder(
          int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);  } else {
          return messagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public java.util.List<? extends cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessageOrBuilder> 
           getMessagesOrBuilderList() {
        if (messagesBuilder_ != null) {
          return messagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messages_);
        }
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.Builder addMessagesBuilder() {
        return getMessagesFieldBuilder().addBuilder(
            cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.Builder addMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().addBuilder(
            index, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .NStateMessage messages = 1;</code>
       */
      public java.util.List<cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.Builder> 
           getMessagesBuilderList() {
        return getMessagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.Builder, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessageOrBuilder> 
          getMessagesFieldBuilder() {
        if (messagesBuilder_ == null) {
          messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessage.Builder, cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessageOrBuilder>(
                  messages_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          messages_ = null;
        }
        return messagesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NStateMessages)
    }

    // @@protoc_insertion_point(class_scope:NStateMessages)
    private static final cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages();
    }

    public static cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NStateMessages>
        PARSER = new com.google.protobuf.AbstractParser<NStateMessages>() {
      @java.lang.Override
      public NStateMessages parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NStateMessages(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NStateMessages> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NStateMessages> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.jisol.ngame.demo.proto.cocos.FStateMessage.NStateMessages getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NStateVec3_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NStateVec3_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NStateMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NStateMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NStateMessage_StatesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NStateMessage_StatesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NStateMessages_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NStateMessages_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023FStateMessage.proto\032\031google/protobuf/a" +
      "ny.proto\"-\n\nNStateVec3\022\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002" +
      " \001(\001\022\t\n\001z\030\003 \001(\001\"\235\001\n\rNStateMessage\022\013\n\003nId" +
      "\030\001 \001(\003\022\016\n\006prefab\030\002 \001(\003\022*\n\006states\030\003 \003(\0132\032" +
      ".NStateMessage.StatesEntry\032C\n\013StatesEntr" +
      "y\022\013\n\003key\030\001 \001(\t\022#\n\005value\030\002 \001(\0132\024.google.p" +
      "rotobuf.Any:\0028\001\"2\n\016NStateMessages\022 \n\010mes" +
      "sages\030\001 \003(\0132\016.NStateMessageB!\n\037cn.jisol." +
      "ngame.demo.proto.cocosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_NStateVec3_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NStateVec3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NStateVec3_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_NStateMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NStateMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NStateMessage_descriptor,
        new java.lang.String[] { "NId", "Prefab", "States", });
    internal_static_NStateMessage_StatesEntry_descriptor =
      internal_static_NStateMessage_descriptor.getNestedTypes().get(0);
    internal_static_NStateMessage_StatesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NStateMessage_StatesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_NStateMessages_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_NStateMessages_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NStateMessages_descriptor,
        new java.lang.String[] { "Messages", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
