// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSyncFPSInfo.proto

package cn.jisol.ngame.proto.maction;

public final class MSyncFPSInfo {
  private MSyncFPSInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MVector3OrBuilder extends
      // @@protoc_insertion_point(interface_extends:MVector3)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float x = 1;</code>
     * @return The x.
     */
    float getX();

    /**
     * <code>float y = 2;</code>
     * @return The y.
     */
    float getY();

    /**
     * <code>float z = 3;</code>
     * @return The z.
     */
    float getZ();
  }
  /**
   * Protobuf type {@code MVector3}
   */
  public  static final class MVector3 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MVector3)
      MVector3OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MVector3.newBuilder() to construct.
    private MVector3(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MVector3() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MVector3();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MVector3(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              x_ = input.readFloat();
              break;
            }
            case 21: {

              y_ = input.readFloat();
              break;
            }
            case 29: {

              z_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.jisol.ngame.proto.maction.MSyncFPSInfo.internal_static_MVector3_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.jisol.ngame.proto.maction.MSyncFPSInfo.internal_static_MVector3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.class, cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <code>float x = 1;</code>
     * @return The x.
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <code>float y = 2;</code>
     * @return The y.
     */
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_;
    /**
     * <code>float z = 3;</code>
     * @return The z.
     */
    public float getZ() {
      return z_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0F) {
        output.writeFloat(1, x_);
      }
      if (y_ != 0F) {
        output.writeFloat(2, y_);
      }
      if (z_ != 0F) {
        output.writeFloat(3, z_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (y_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (z_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3)) {
        return super.equals(obj);
      }
      cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 other = (cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3) obj;

      if (java.lang.Float.floatToIntBits(getX())
          != java.lang.Float.floatToIntBits(
              other.getX())) return false;
      if (java.lang.Float.floatToIntBits(getY())
          != java.lang.Float.floatToIntBits(
              other.getY())) return false;
      if (java.lang.Float.floatToIntBits(getZ())
          != java.lang.Float.floatToIntBits(
              other.getZ())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getX());
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getY());
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getZ());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MVector3}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MVector3)
        cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.jisol.ngame.proto.maction.MSyncFPSInfo.internal_static_MVector3_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.jisol.ngame.proto.maction.MSyncFPSInfo.internal_static_MVector3_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.class, cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.Builder.class);
      }

      // Construct using cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = 0F;

        y_ = 0F;

        z_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.jisol.ngame.proto.maction.MSyncFPSInfo.internal_static_MVector3_descriptor;
      }

      @java.lang.Override
      public cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 getDefaultInstanceForType() {
        return cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.getDefaultInstance();
      }

      @java.lang.Override
      public cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 build() {
        cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 buildPartial() {
        cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 result = new cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3(this);
        result.x_ = x_;
        result.y_ = y_;
        result.z_ = z_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3) {
          return mergeFrom((cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 other) {
        if (other == cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.getDefaultInstance()) return this;
        if (other.getX() != 0F) {
          setX(other.getX());
        }
        if (other.getY() != 0F) {
          setY(other.getY());
        }
        if (other.getZ() != 0F) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float x_ ;
      /**
       * <code>float x = 1;</code>
       * @return The x.
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>float x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(float value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>float y = 2;</code>
       * @return The y.
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>float y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(float value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>float z = 3;</code>
       * @return The z.
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>float z = 3;</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(float value) {
        
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float z = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        
        z_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MVector3)
    }

    // @@protoc_insertion_point(class_scope:MVector3)
    private static final cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3();
    }

    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MVector3>
        PARSER = new com.google.protobuf.AbstractParser<MVector3>() {
      @java.lang.Override
      public MVector3 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MVector3(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MVector3> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MVector3> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NAction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 uuid = 1;</code>
     * @return The uuid.
     */
    int getUuid();

    /**
     * <code>.MVector3 pos = 2;</code>
     * @return Whether the pos field is set.
     */
    boolean hasPos();
    /**
     * <code>.MVector3 pos = 2;</code>
     * @return The pos.
     */
    cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 getPos();
    /**
     * <code>.MVector3 pos = 2;</code>
     */
    cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3OrBuilder getPosOrBuilder();

    /**
     * <code>.MVector3 rot = 3;</code>
     * @return Whether the rot field is set.
     */
    boolean hasRot();
    /**
     * <code>.MVector3 rot = 3;</code>
     * @return The rot.
     */
    cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 getRot();
    /**
     * <code>.MVector3 rot = 3;</code>
     */
    cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3OrBuilder getRotOrBuilder();
  }
  /**
   * Protobuf type {@code NAction}
   */
  public  static final class NAction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NAction)
      NActionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NAction.newBuilder() to construct.
    private NAction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NAction() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NAction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              uuid_ = input.readInt32();
              break;
            }
            case 18: {
              cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.Builder subBuilder = null;
              if (pos_ != null) {
                subBuilder = pos_.toBuilder();
              }
              pos_ = input.readMessage(cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pos_);
                pos_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.Builder subBuilder = null;
              if (rot_ != null) {
                subBuilder = rot_.toBuilder();
              }
              rot_ = input.readMessage(cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rot_);
                rot_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.jisol.ngame.proto.maction.MSyncFPSInfo.internal_static_NAction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.jisol.ngame.proto.maction.MSyncFPSInfo.internal_static_NAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction.class, cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction.Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private int uuid_;
    /**
     * <code>int32 uuid = 1;</code>
     * @return The uuid.
     */
    public int getUuid() {
      return uuid_;
    }

    public static final int POS_FIELD_NUMBER = 2;
    private cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 pos_;
    /**
     * <code>.MVector3 pos = 2;</code>
     * @return Whether the pos field is set.
     */
    public boolean hasPos() {
      return pos_ != null;
    }
    /**
     * <code>.MVector3 pos = 2;</code>
     * @return The pos.
     */
    public cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 getPos() {
      return pos_ == null ? cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.getDefaultInstance() : pos_;
    }
    /**
     * <code>.MVector3 pos = 2;</code>
     */
    public cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3OrBuilder getPosOrBuilder() {
      return getPos();
    }

    public static final int ROT_FIELD_NUMBER = 3;
    private cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 rot_;
    /**
     * <code>.MVector3 rot = 3;</code>
     * @return Whether the rot field is set.
     */
    public boolean hasRot() {
      return rot_ != null;
    }
    /**
     * <code>.MVector3 rot = 3;</code>
     * @return The rot.
     */
    public cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 getRot() {
      return rot_ == null ? cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.getDefaultInstance() : rot_;
    }
    /**
     * <code>.MVector3 rot = 3;</code>
     */
    public cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3OrBuilder getRotOrBuilder() {
      return getRot();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uuid_ != 0) {
        output.writeInt32(1, uuid_);
      }
      if (pos_ != null) {
        output.writeMessage(2, getPos());
      }
      if (rot_ != null) {
        output.writeMessage(3, getRot());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uuid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uuid_);
      }
      if (pos_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPos());
      }
      if (rot_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getRot());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction)) {
        return super.equals(obj);
      }
      cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction other = (cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction) obj;

      if (getUuid()
          != other.getUuid()) return false;
      if (hasPos() != other.hasPos()) return false;
      if (hasPos()) {
        if (!getPos()
            .equals(other.getPos())) return false;
      }
      if (hasRot() != other.hasRot()) return false;
      if (hasRot()) {
        if (!getRot()
            .equals(other.getRot())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid();
      if (hasPos()) {
        hash = (37 * hash) + POS_FIELD_NUMBER;
        hash = (53 * hash) + getPos().hashCode();
      }
      if (hasRot()) {
        hash = (37 * hash) + ROT_FIELD_NUMBER;
        hash = (53 * hash) + getRot().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NAction)
        cn.jisol.ngame.proto.maction.MSyncFPSInfo.NActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.jisol.ngame.proto.maction.MSyncFPSInfo.internal_static_NAction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.jisol.ngame.proto.maction.MSyncFPSInfo.internal_static_NAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction.class, cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction.Builder.class);
      }

      // Construct using cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uuid_ = 0;

        if (posBuilder_ == null) {
          pos_ = null;
        } else {
          pos_ = null;
          posBuilder_ = null;
        }
        if (rotBuilder_ == null) {
          rot_ = null;
        } else {
          rot_ = null;
          rotBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.jisol.ngame.proto.maction.MSyncFPSInfo.internal_static_NAction_descriptor;
      }

      @java.lang.Override
      public cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction getDefaultInstanceForType() {
        return cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction.getDefaultInstance();
      }

      @java.lang.Override
      public cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction build() {
        cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction buildPartial() {
        cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction result = new cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction(this);
        result.uuid_ = uuid_;
        if (posBuilder_ == null) {
          result.pos_ = pos_;
        } else {
          result.pos_ = posBuilder_.build();
        }
        if (rotBuilder_ == null) {
          result.rot_ = rot_;
        } else {
          result.rot_ = rotBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction) {
          return mergeFrom((cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction other) {
        if (other == cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction.getDefaultInstance()) return this;
        if (other.getUuid() != 0) {
          setUuid(other.getUuid());
        }
        if (other.hasPos()) {
          mergePos(other.getPos());
        }
        if (other.hasRot()) {
          mergeRot(other.getRot());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int uuid_ ;
      /**
       * <code>int32 uuid = 1;</code>
       * @return The uuid.
       */
      public int getUuid() {
        return uuid_;
      }
      /**
       * <code>int32 uuid = 1;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(int value) {
        
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uuid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        
        uuid_ = 0;
        onChanged();
        return this;
      }

      private cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 pos_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3, cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.Builder, cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3OrBuilder> posBuilder_;
      /**
       * <code>.MVector3 pos = 2;</code>
       * @return Whether the pos field is set.
       */
      public boolean hasPos() {
        return posBuilder_ != null || pos_ != null;
      }
      /**
       * <code>.MVector3 pos = 2;</code>
       * @return The pos.
       */
      public cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 getPos() {
        if (posBuilder_ == null) {
          return pos_ == null ? cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.getDefaultInstance() : pos_;
        } else {
          return posBuilder_.getMessage();
        }
      }
      /**
       * <code>.MVector3 pos = 2;</code>
       */
      public Builder setPos(cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 value) {
        if (posBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pos_ = value;
          onChanged();
        } else {
          posBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.MVector3 pos = 2;</code>
       */
      public Builder setPos(
          cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.Builder builderForValue) {
        if (posBuilder_ == null) {
          pos_ = builderForValue.build();
          onChanged();
        } else {
          posBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.MVector3 pos = 2;</code>
       */
      public Builder mergePos(cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 value) {
        if (posBuilder_ == null) {
          if (pos_ != null) {
            pos_ =
              cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.newBuilder(pos_).mergeFrom(value).buildPartial();
          } else {
            pos_ = value;
          }
          onChanged();
        } else {
          posBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.MVector3 pos = 2;</code>
       */
      public Builder clearPos() {
        if (posBuilder_ == null) {
          pos_ = null;
          onChanged();
        } else {
          pos_ = null;
          posBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.MVector3 pos = 2;</code>
       */
      public cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.Builder getPosBuilder() {
        
        onChanged();
        return getPosFieldBuilder().getBuilder();
      }
      /**
       * <code>.MVector3 pos = 2;</code>
       */
      public cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3OrBuilder getPosOrBuilder() {
        if (posBuilder_ != null) {
          return posBuilder_.getMessageOrBuilder();
        } else {
          return pos_ == null ?
              cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.getDefaultInstance() : pos_;
        }
      }
      /**
       * <code>.MVector3 pos = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3, cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.Builder, cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3OrBuilder> 
          getPosFieldBuilder() {
        if (posBuilder_ == null) {
          posBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3, cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.Builder, cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3OrBuilder>(
                  getPos(),
                  getParentForChildren(),
                  isClean());
          pos_ = null;
        }
        return posBuilder_;
      }

      private cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 rot_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3, cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.Builder, cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3OrBuilder> rotBuilder_;
      /**
       * <code>.MVector3 rot = 3;</code>
       * @return Whether the rot field is set.
       */
      public boolean hasRot() {
        return rotBuilder_ != null || rot_ != null;
      }
      /**
       * <code>.MVector3 rot = 3;</code>
       * @return The rot.
       */
      public cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 getRot() {
        if (rotBuilder_ == null) {
          return rot_ == null ? cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.getDefaultInstance() : rot_;
        } else {
          return rotBuilder_.getMessage();
        }
      }
      /**
       * <code>.MVector3 rot = 3;</code>
       */
      public Builder setRot(cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 value) {
        if (rotBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rot_ = value;
          onChanged();
        } else {
          rotBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.MVector3 rot = 3;</code>
       */
      public Builder setRot(
          cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.Builder builderForValue) {
        if (rotBuilder_ == null) {
          rot_ = builderForValue.build();
          onChanged();
        } else {
          rotBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.MVector3 rot = 3;</code>
       */
      public Builder mergeRot(cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3 value) {
        if (rotBuilder_ == null) {
          if (rot_ != null) {
            rot_ =
              cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.newBuilder(rot_).mergeFrom(value).buildPartial();
          } else {
            rot_ = value;
          }
          onChanged();
        } else {
          rotBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.MVector3 rot = 3;</code>
       */
      public Builder clearRot() {
        if (rotBuilder_ == null) {
          rot_ = null;
          onChanged();
        } else {
          rot_ = null;
          rotBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.MVector3 rot = 3;</code>
       */
      public cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.Builder getRotBuilder() {
        
        onChanged();
        return getRotFieldBuilder().getBuilder();
      }
      /**
       * <code>.MVector3 rot = 3;</code>
       */
      public cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3OrBuilder getRotOrBuilder() {
        if (rotBuilder_ != null) {
          return rotBuilder_.getMessageOrBuilder();
        } else {
          return rot_ == null ?
              cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.getDefaultInstance() : rot_;
        }
      }
      /**
       * <code>.MVector3 rot = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3, cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.Builder, cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3OrBuilder> 
          getRotFieldBuilder() {
        if (rotBuilder_ == null) {
          rotBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3, cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3.Builder, cn.jisol.ngame.proto.maction.MSyncFPSInfo.MVector3OrBuilder>(
                  getRot(),
                  getParentForChildren(),
                  isClean());
          rot_ = null;
        }
        return rotBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NAction)
    }

    // @@protoc_insertion_point(class_scope:NAction)
    private static final cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction();
    }

    public static cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NAction>
        PARSER = new com.google.protobuf.AbstractParser<NAction>() {
      @java.lang.Override
      public NAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NAction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NAction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NAction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.jisol.ngame.proto.maction.MSyncFPSInfo.NAction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MVector3_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MVector3_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NAction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NAction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MSyncFPSInfo.proto\"+\n\010MVector3\022\t\n\001x\030\001 " +
      "\001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\"G\n\007NAction\022\014\n\004" +
      "uuid\030\001 \001(\005\022\026\n\003pos\030\002 \001(\0132\t.MVector3\022\026\n\003ro" +
      "t\030\003 \001(\0132\t.MVector3B/\n\034cn.jisol.ngame.pro" +
      "to.maction\252\002\016NGame.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MVector3_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MVector3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MVector3_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_NAction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NAction_descriptor,
        new java.lang.String[] { "Uuid", "Pos", "Rot", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
