// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DActorOwner.proto

package cn.jisol.ngame.demo.proto.sync;

public final class DActorOwnerOuterClass {
  private DActorOwnerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DActorOwnerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DActorOwner)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *Actor UUID
     * </pre>
     *
     * <code>int32 uuid = 1;</code>
     * @return The uuid.
     */
    int getUuid();

    /**
     * <pre>
     *Actor 权重
     * </pre>
     *
     * <code>int32 owner = 2;</code>
     * @return The owner.
     */
    int getOwner();

    /**
     * <pre>
     *是否是自己的权重
     * </pre>
     *
     * <code>bool isOwn = 3;</code>
     * @return The isOwn.
     */
    boolean getIsOwn();
  }
  /**
   * Protobuf type {@code DActorOwner}
   */
  public  static final class DActorOwner extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DActorOwner)
      DActorOwnerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DActorOwner.newBuilder() to construct.
    private DActorOwner(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DActorOwner() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DActorOwner();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DActorOwner(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              uuid_ = input.readInt32();
              break;
            }
            case 16: {

              owner_ = input.readInt32();
              break;
            }
            case 24: {

              isOwn_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.internal_static_DActorOwner_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.internal_static_DActorOwner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner.class, cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner.Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private int uuid_;
    /**
     * <pre>
     *Actor UUID
     * </pre>
     *
     * <code>int32 uuid = 1;</code>
     * @return The uuid.
     */
    public int getUuid() {
      return uuid_;
    }

    public static final int OWNER_FIELD_NUMBER = 2;
    private int owner_;
    /**
     * <pre>
     *Actor 权重
     * </pre>
     *
     * <code>int32 owner = 2;</code>
     * @return The owner.
     */
    public int getOwner() {
      return owner_;
    }

    public static final int ISOWN_FIELD_NUMBER = 3;
    private boolean isOwn_;
    /**
     * <pre>
     *是否是自己的权重
     * </pre>
     *
     * <code>bool isOwn = 3;</code>
     * @return The isOwn.
     */
    public boolean getIsOwn() {
      return isOwn_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uuid_ != 0) {
        output.writeInt32(1, uuid_);
      }
      if (owner_ != 0) {
        output.writeInt32(2, owner_);
      }
      if (isOwn_ != false) {
        output.writeBool(3, isOwn_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uuid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uuid_);
      }
      if (owner_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, owner_);
      }
      if (isOwn_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isOwn_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner)) {
        return super.equals(obj);
      }
      cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner other = (cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner) obj;

      if (getUuid()
          != other.getUuid()) return false;
      if (getOwner()
          != other.getOwner()) return false;
      if (getIsOwn()
          != other.getIsOwn()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid();
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner();
      hash = (37 * hash) + ISOWN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsOwn());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DActorOwner}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DActorOwner)
        cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwnerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.internal_static_DActorOwner_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.internal_static_DActorOwner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner.class, cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner.Builder.class);
      }

      // Construct using cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uuid_ = 0;

        owner_ = 0;

        isOwn_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.internal_static_DActorOwner_descriptor;
      }

      @java.lang.Override
      public cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner getDefaultInstanceForType() {
        return cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner.getDefaultInstance();
      }

      @java.lang.Override
      public cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner build() {
        cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner buildPartial() {
        cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner result = new cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner(this);
        result.uuid_ = uuid_;
        result.owner_ = owner_;
        result.isOwn_ = isOwn_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner) {
          return mergeFrom((cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner other) {
        if (other == cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner.getDefaultInstance()) return this;
        if (other.getUuid() != 0) {
          setUuid(other.getUuid());
        }
        if (other.getOwner() != 0) {
          setOwner(other.getOwner());
        }
        if (other.getIsOwn() != false) {
          setIsOwn(other.getIsOwn());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int uuid_ ;
      /**
       * <pre>
       *Actor UUID
       * </pre>
       *
       * <code>int32 uuid = 1;</code>
       * @return The uuid.
       */
      public int getUuid() {
        return uuid_;
      }
      /**
       * <pre>
       *Actor UUID
       * </pre>
       *
       * <code>int32 uuid = 1;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(int value) {
        
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Actor UUID
       * </pre>
       *
       * <code>int32 uuid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        
        uuid_ = 0;
        onChanged();
        return this;
      }

      private int owner_ ;
      /**
       * <pre>
       *Actor 权重
       * </pre>
       *
       * <code>int32 owner = 2;</code>
       * @return The owner.
       */
      public int getOwner() {
        return owner_;
      }
      /**
       * <pre>
       *Actor 权重
       * </pre>
       *
       * <code>int32 owner = 2;</code>
       * @param value The owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwner(int value) {
        
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Actor 权重
       * </pre>
       *
       * <code>int32 owner = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwner() {
        
        owner_ = 0;
        onChanged();
        return this;
      }

      private boolean isOwn_ ;
      /**
       * <pre>
       *是否是自己的权重
       * </pre>
       *
       * <code>bool isOwn = 3;</code>
       * @return The isOwn.
       */
      public boolean getIsOwn() {
        return isOwn_;
      }
      /**
       * <pre>
       *是否是自己的权重
       * </pre>
       *
       * <code>bool isOwn = 3;</code>
       * @param value The isOwn to set.
       * @return This builder for chaining.
       */
      public Builder setIsOwn(boolean value) {
        
        isOwn_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否是自己的权重
       * </pre>
       *
       * <code>bool isOwn = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsOwn() {
        
        isOwn_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DActorOwner)
    }

    // @@protoc_insertion_point(class_scope:DActorOwner)
    private static final cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner();
    }

    public static cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DActorOwner>
        PARSER = new com.google.protobuf.AbstractParser<DActorOwner>() {
      @java.lang.Override
      public DActorOwner parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DActorOwner(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DActorOwner> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DActorOwner> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.jisol.ngame.demo.proto.sync.DActorOwnerOuterClass.DActorOwner getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DActorOwner_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DActorOwner_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021DActorOwner.proto\"9\n\013DActorOwner\022\014\n\004uu" +
      "id\030\001 \001(\005\022\r\n\005owner\030\002 \001(\005\022\r\n\005isOwn\030\003 \001(\010B " +
      "\n\036cn.jisol.ngame.demo.proto.syncb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DActorOwner_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DActorOwner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DActorOwner_descriptor,
        new java.lang.String[] { "Uuid", "Owner", "IsOwn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
