// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DSyncInfos.proto

package cn.jisol.ngame.demo.proto.sync;

public final class DSyncInfosOuterClass {
  private DSyncInfosOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DSyncInfosOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DSyncInfos)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *帧索引
     * </pre>
     *
     * <code>int32 index = 1;</code>
     * @return The index.
     */
    int getIndex();

    /**
     * <pre>
     *帧操作列表
     * </pre>
     *
     * <code>repeated .google.protobuf.Any message = 2;</code>
     */
    java.util.List<com.google.protobuf.Any> 
        getMessageList();
    /**
     * <pre>
     *帧操作列表
     * </pre>
     *
     * <code>repeated .google.protobuf.Any message = 2;</code>
     */
    com.google.protobuf.Any getMessage(int index);
    /**
     * <pre>
     *帧操作列表
     * </pre>
     *
     * <code>repeated .google.protobuf.Any message = 2;</code>
     */
    int getMessageCount();
    /**
     * <pre>
     *帧操作列表
     * </pre>
     *
     * <code>repeated .google.protobuf.Any message = 2;</code>
     */
    java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getMessageOrBuilderList();
    /**
     * <pre>
     *帧操作列表
     * </pre>
     *
     * <code>repeated .google.protobuf.Any message = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getMessageOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DSyncInfos}
   */
  public  static final class DSyncInfos extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DSyncInfos)
      DSyncInfosOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DSyncInfos.newBuilder() to construct.
    private DSyncInfos(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DSyncInfos() {
      message_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DSyncInfos();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DSyncInfos(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              index_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                message_ = new java.util.ArrayList<com.google.protobuf.Any>();
                mutable_bitField0_ |= 0x00000001;
              }
              message_.add(
                  input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          message_ = java.util.Collections.unmodifiableList(message_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.internal_static_DSyncInfos_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.internal_static_DSyncInfos_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos.class, cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <pre>
     *帧索引
     * </pre>
     *
     * <code>int32 index = 1;</code>
     * @return The index.
     */
    public int getIndex() {
      return index_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.Any> message_;
    /**
     * <pre>
     *帧操作列表
     * </pre>
     *
     * <code>repeated .google.protobuf.Any message = 2;</code>
     */
    public java.util.List<com.google.protobuf.Any> getMessageList() {
      return message_;
    }
    /**
     * <pre>
     *帧操作列表
     * </pre>
     *
     * <code>repeated .google.protobuf.Any message = 2;</code>
     */
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getMessageOrBuilderList() {
      return message_;
    }
    /**
     * <pre>
     *帧操作列表
     * </pre>
     *
     * <code>repeated .google.protobuf.Any message = 2;</code>
     */
    public int getMessageCount() {
      return message_.size();
    }
    /**
     * <pre>
     *帧操作列表
     * </pre>
     *
     * <code>repeated .google.protobuf.Any message = 2;</code>
     */
    public com.google.protobuf.Any getMessage(int index) {
      return message_.get(index);
    }
    /**
     * <pre>
     *帧操作列表
     * </pre>
     *
     * <code>repeated .google.protobuf.Any message = 2;</code>
     */
    public com.google.protobuf.AnyOrBuilder getMessageOrBuilder(
        int index) {
      return message_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0) {
        output.writeInt32(1, index_);
      }
      for (int i = 0; i < message_.size(); i++) {
        output.writeMessage(2, message_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, index_);
      }
      for (int i = 0; i < message_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, message_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos)) {
        return super.equals(obj);
      }
      cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos other = (cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos) obj;

      if (getIndex()
          != other.getIndex()) return false;
      if (!getMessageList()
          .equals(other.getMessageList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      if (getMessageCount() > 0) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessageList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DSyncInfos}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DSyncInfos)
        cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfosOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.internal_static_DSyncInfos_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.internal_static_DSyncInfos_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos.class, cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos.Builder.class);
      }

      // Construct using cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMessageFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        index_ = 0;

        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          messageBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.internal_static_DSyncInfos_descriptor;
      }

      @java.lang.Override
      public cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos getDefaultInstanceForType() {
        return cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos.getDefaultInstance();
      }

      @java.lang.Override
      public cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos build() {
        cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos buildPartial() {
        cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos result = new cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos(this);
        int from_bitField0_ = bitField0_;
        result.index_ = index_;
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            message_ = java.util.Collections.unmodifiableList(message_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos) {
          return mergeFrom((cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos other) {
        if (other == cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos.getDefaultInstance()) return this;
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        if (messageBuilder_ == null) {
          if (!other.message_.isEmpty()) {
            if (message_.isEmpty()) {
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessageIsMutable();
              message_.addAll(other.message_);
            }
            onChanged();
          }
        } else {
          if (!other.message_.isEmpty()) {
            if (messageBuilder_.isEmpty()) {
              messageBuilder_.dispose();
              messageBuilder_ = null;
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMessageFieldBuilder() : null;
            } else {
              messageBuilder_.addAllMessages(other.message_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int index_ ;
      /**
       * <pre>
       *帧索引
       * </pre>
       *
       * <code>int32 index = 1;</code>
       * @return The index.
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <pre>
       *帧索引
       * </pre>
       *
       * <code>int32 index = 1;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *帧索引
       * </pre>
       *
       * <code>int32 index = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.Any> message_ =
        java.util.Collections.emptyList();
      private void ensureMessageIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          message_ = new java.util.ArrayList<com.google.protobuf.Any>(message_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> messageBuilder_;

      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public java.util.List<com.google.protobuf.Any> getMessageList() {
        if (messageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(message_);
        } else {
          return messageBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public int getMessageCount() {
        if (messageBuilder_ == null) {
          return message_.size();
        } else {
          return messageBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public com.google.protobuf.Any getMessage(int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);
        } else {
          return messageBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public Builder setMessage(
          int index, com.google.protobuf.Any value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.set(index, value);
          onChanged();
        } else {
          messageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public Builder setMessage(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.set(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public Builder addMessage(com.google.protobuf.Any value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(value);
          onChanged();
        } else {
          messageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public Builder addMessage(
          int index, com.google.protobuf.Any value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(index, value);
          onChanged();
        } else {
          messageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public Builder addMessage(
          com.google.protobuf.Any.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public Builder addMessage(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public Builder addAllMessage(
          java.lang.Iterable<? extends com.google.protobuf.Any> values) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, message_);
          onChanged();
        } else {
          messageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messageBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public Builder removeMessage(int index) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.remove(index);
          onChanged();
        } else {
          messageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public com.google.protobuf.Any.Builder getMessageBuilder(
          int index) {
        return getMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getMessageOrBuilder(
          int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);  } else {
          return messageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
           getMessageOrBuilderList() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(message_);
        }
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public com.google.protobuf.Any.Builder addMessageBuilder() {
        return getMessageFieldBuilder().addBuilder(
            com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public com.google.protobuf.Any.Builder addMessageBuilder(
          int index) {
        return getMessageFieldBuilder().addBuilder(
            index, com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <pre>
       *帧操作列表
       * </pre>
       *
       * <code>repeated .google.protobuf.Any message = 2;</code>
       */
      public java.util.List<com.google.protobuf.Any.Builder> 
           getMessageBuilderList() {
        return getMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  message_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DSyncInfos)
    }

    // @@protoc_insertion_point(class_scope:DSyncInfos)
    private static final cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos();
    }

    public static cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DSyncInfos>
        PARSER = new com.google.protobuf.AbstractParser<DSyncInfos>() {
      @java.lang.Override
      public DSyncInfos parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DSyncInfos(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DSyncInfos> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DSyncInfos> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.jisol.ngame.demo.proto.sync.DSyncInfosOuterClass.DSyncInfos getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DSyncInfos_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DSyncInfos_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020DSyncInfos.proto\032\031google/protobuf/any." +
      "proto\"B\n\nDSyncInfos\022\r\n\005index\030\001 \001(\005\022%\n\007me" +
      "ssage\030\002 \003(\0132\024.google.protobuf.AnyB \n\036cn." +
      "jisol.ngame.demo.proto.syncb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_DSyncInfos_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DSyncInfos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DSyncInfos_descriptor,
        new java.lang.String[] { "Index", "Message", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
